Drivers:GPU:DRM
mtk_drm_crtc.c:7035:3: error: 'mtk_dprec_logger_pr' requires 'double' type support, but ABI 'aapcs' does not support it

So we calculate the division in advance.
Threshold = round( 1_000_000_000 / 46.1 ) ≈ round( 21691973.9696 ) ≈ 21691974